### PR TITLE
Add Mysql 8 SRID support

### PR DESCRIPTION
**Pull request by Gemui**
I was using the package and really have problem with SRID specially for gps coordinates, So I have been added 

- Support for SRID with Geometry types
```php
$coordinates = Place::create([
    'name' => 'London Eye',
    'coordinates' => new Point(12.455363273620605, 41.90746728266806, 4326)
]);
```

- Set SRID value from global default value or from the object

```php
  'connections' => [
        'mysql' => [
            'driver' => 'mysql',
            'default_srid' => env('DEFAULT_SRID',0),
        ],
    ]
```
- Add Ability for working with SRID 4326 (WGS84), The problem with this SRID is how it saving the points x,y in database
default for Mysql is lng,lat but only for 4326 It save with lat,lng
So I added `axis` parameter
```php
return DB::raw("ST_GeomFromText('{$wkt}', {$geometry->getSrid()}, 'axis-order=long-lat')");
```
now every time database with working (lng,lat) logic with considerate for SRID 4326 (WGS84)

- add `whereSrid` method that help to filter 
```php
Place::create(['coordinates' => new Point(12.455363273620605, 41.90746728266806, 4326)]);

Place::query()
    ->whereSrid('coordinates', '=', 4326)
    ->exists(); // true
```
- Write tests for SRID

### CODE REVIEW

**Comment by Gemui** [comment]
#27

**Comment by MatanYadaev** [comment]
Hi @Gemui, I'm very happy to have this PR, thanks for your work.
I'll review it tomorrow.
Meanwhile, could you please fix the CI results? Run `composer run phpinsights fix` `composer run php-cs-fixer` `composer run phpstan`

**Comment by Gemui** [comment]
Hi @MatanYadaev 
I fixed the CI results then #43 made a conflict with this PR.
I fixed the conflict also, but I think `phpinsights` need to update indentation config because it change the code style to `4` spaces not 2 .
I hope you reviewed the code to start merging before another conflict .

**Comment by MatanYadaev** [comment]
@Gemui Sorry, it will take me a few more days until I'll merge this feature. I'm planning on writing more tests (and refactor current tests), and I'm not sure about the default SRID config.

**Comment by MatanYadaev** [comment]
@Gemui Please don't waste time fixing the conflicts. There are going to be more of them in the next few days.

**Comment by Gemui** [comment]
> @Gemui Please don't waste time fixing the conflicts. There are going to be more of them in the next few days.

No problem I leave it now, but if you have a pattern or something need to implemented with it I can help you to fast the process

**Comment by MatanYadaev** [comment]
@Gemui Thanks for the help, I took your code and implemented it here: https://github.com/MatanYadaev/laravel-eloquent-spatial/pull/47

**Pull request closed without merging**
