### PR TITLE
Add support for convex hulls

### PR DESCRIPTION
**Pull request by Riley19280**
Add support for using the [ST_ConvexHull](https://dev.mysql.com/doc/refman/8.0/en/spatial-operator-functions.html#function_st-convexhull) funciton.

I broke this out of the `SpatialBuilder` class because it does not operate on a model, only on geometry. For example, this query 
```sql
select ST_CONVEXHULL(ST_GeomFromText('MULTIPOINT(-1 -1, 1 -1, 1 1, -1 1, -1 -1, 0 0)', 0, 'axis-order=long-lat')) as convex_hull
``` 
results from 
`SpatialQuery::make()->convexHull($geometry)`

### CODE REVIEW

**Comment by MatanYadaev** [comment]
Hi @Riley19280, thanks for the PR!
Can you please explain to me what convex hull means? I'm not familiar with this functionality.
And, please explain me the use case. Why do you need this function?

**Comment by Riley19280** [comment]
> Hi @Riley19280, thanks for the PR! Can you please explain to me what convex hull means? I'm not familiar with this functionality. And, please explain me the use case. Why do you need this function?

A convex hull is a shape that encompasses all points given
Screen Shot 2023-02-28 at 11 19 18 AM

Im my use case this is exactly what I need

**Comment by Riley19280** [comment]
> Thanks for the explanation. Isn't it better to implement this algorithm in PHP and save the IO operation to the DB?

Could be, I am not sure though. I don't want to write it myself when I can have the database do it though. I'm sure whoever implemented it on a database did it as efficiently as they could

**Comment by MatanYadaev** [comment]
I'm sorry. I appreciate your time, but I prefer not to mess up this package with a new builder class. I assume this use case isn't very common.

I suggest you use this code in your project, on top of this package.

Let me know if there's anything else I can help with.

**Comment by Riley19280** [comment]
I feel that having a go-to package for all spatial database queries is important. There are plenty of other spatial database functions available that could be added to the builder class, further extending the capabilities and objects provided by this package. Converting to/from another packages Geometry classes would be a hassle

**Comment by MatanYadaev** [comment]
Ok, I see what you mean. Can you make the class not inherit from `Builder`?
I don't have an ideal design yet, but the direction should be something like this `GeometryEngine::make($connection)->convexHull($multiPoint)`, when `make`'s first parameter is optional, and the function returns a `Polygon` without the need to do `->first()->convex_hull`

**Comment by Riley19280** [comment]
> Ok, I see what you mean. Can you make the class not inherit from `Builder`? I don't have an ideal design yet, but the direction should be something like this `GeometryUtils::make($connection)->convexHull($multiPoint)`, when `make`'s first parameter is optional, and the function returns a `Polygon` without the need to do `->first()->convex_hull`

I think returning a geometry class directly makes the most sense. Wanted to do that originally but it was too closely tied to queries. I like the direction it's headed now. Let me know what you think

**Comment by MatanYadaev** [comment]
It looks great, I made some refactoring, can you check it? https://github.com/MatanYadaev/laravel-eloquent-spatial/tree/convex-hull
I removed the `distanceSphere`, I prefer it to be in a separated PR.

**Comment by Riley19280** [comment]
> It looks great, I made some refactoring, can you check it? [4237bf0](https://github.com/MatanYadaev/laravel-eloquent-spatial/commit/4237bf0ef477d007a76b12fbff25a08c4d1521a7) I removed the `distanceSphere`, I prefer it to be in a separated PR.

Looks mostly good to me! Only thing i dislike is the `toExpressionString` function polluting the global scope, since it's not in any class. Globally available functions are usually used for helper methods and such, but this helper is really only useful to the package internals.

**Comment by MatanYadaev** [comment]
@Riley19280 Can you fix the PR to include my refactoring?

**Pull request closed without merging**
