### PR TITLE
prevent json_encode error 5

### LINKED ISSUE #55: Unable to JSON encode payload. Error code: 5
Thank you for your work on this package! I've been fighting an issue for the past week that I can't find a resolution to. I don't know if this is an issue with this package or Laravel but I thought that I would start here.

I have a queued job that has an object (not a model) as constructor argument. The object has property that is a model with a coordinates (Point) attribute. 

**something like:**
```php
class Report
{
  $account = null;
  public function __construct(Model $account) {
    $this->account = $account
  }
}

$account = Account::first();
MakeReport::dispatch(new Report($account));
```

The coordinates attribute is properly casted on the Account model
```php
protected $casts = [
    'coordinates' => Point::class
];
```

The problem is that the coordinates are not being serialized by laravel and I get the error: 
`Illuminate\ Queue\ InvalidPayloadException Unable to JSON encode payload. Error code: 5`

Any ideas? I'm starting to lose my mind on this.

PHP 8.1.10
Laravel 9.28.0

### PR DESCRIPTION
**Pull request by d0m4te**
immediately apply casting to geometry objects to prevent errors while trying to json_encode binary data

fixes #55

### CODE REVIEW

**Comment by d0m4te** [comment]
@MatanYadaev sorry, forgot to check against phpstan.

**Review by MatanYadaev — APPROVED** [review]
Thanks!

**Comment by patrickomeara** [comment]
This change breaks the Point casting.

```
TypeError: MatanYadaev\EloquentSpatial\Objects\Geometry::fromWkb(): Argument #1 ($wkb) must be of type string, MatanYadaev\EloquentSpatial\Objects\Point given, called in /Users/pat/Code/web/vendor/matanyadaev/laravel-eloquent-spatial/src/GeometryCast.php on line 47
/Users/pat/Code/web/vendor/matanyadaev/laravel-eloquent-spatial/src/Objects/Geometry.php:72
/Users/pat/Code/web/vendor/matanyadaev/laravel-eloquent-spatial/src/GeometryCast.php:47
/Users/pat/Code/web/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php:816
/Users/pat/Code/web/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php:792
/Users/pat/Code/web/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php:2129
/Users/pat/Code/web/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php:489
/Users/pat/Code/web/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php:443
/Users/pat/Code/web/vendor/matanyadaev/laravel-eloquent-spatial/src/Traits/HasSpatial.php:27
/Users/pat/Code/web/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php:1697
```

It looks like the casting is happening twice and the second time via `getAttribute()` breaks the type.

**Comment by MatanYadaev** [comment]
Hi @patrickomeara , can you please  submit a PR that fixes it?

**Comment by jbajou** [comment]
we're impacted by this, had to downgrade

**Comment by MatanYadaev** [comment]
Please provide examples on how to reproduce this.

**Comment by patrickomeara** [comment]
@jbajou Are you able to send me a code snippet that fails for you? I will add some failing tests and find a solution.

**Comment by jbajou** [comment]
Well, to be honest it's quite simple. We have a `Location` model

```
class Location extends Model
{
    use hasSpatial;
    
    protected $casts = [
        'point' => Point::class
    ];
}
```

Then, in a command (run on AWS SQS, with vapor) we do a `updateOrCreate`:
```
Location::query()
...
->updateOrCreate([
    ...
], [
    'point'           => $centralLocation->point,
]);
```

Here is the stack trace (partial):
```
TypeError MatanYadaev\EloquentSpatial\Objects\Geometry::fromWkb(): Argument #1 ($wkb) must be of type string, MatanYadaev\EloquentSpatial\Objects\Point given, called in /var/task/vendor/matanyadaev/laravel-eloquent-spatial/src/GeometryCast.php on line 47 
    vendor/matanyadaev/laravel-eloquent-spatial/src/Objects/Geometry.php:72 MatanYadaev\EloquentSpatial\Objects\Geometry::fromWkb
    vendor/matanyadaev/laravel-eloquent-spatial/src/GeometryCast.php:47 MatanYadaev\EloquentSpatial\GeometryCast::get
    vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php:816 Illuminate\Database\Eloquent\Model::getClassCastableAttributeValue
    vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php:792 Illuminate\Database\Eloquent\Model::castAttribute
    vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php:2129 Illuminate\Database\Eloquent\Model::transformModelValue
    vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php:489 Illuminate\Database\Eloquent\Model::getAttributeValue
    vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php:443 Illuminate\Database\Eloquent\Model::getAttribute
    vendor/matanyadaev/laravel-eloquent-spatial/src/Traits/HasSpatial.php:27 App\Models\Location::setRawAttributes
```

**Comment by shengslogar** [comment]
Same stack trace over here.

Culprit line:

https://github.com/MatanYadaev/laravel-eloquent-spatial/compare/3.2.0...3.2.1#diff-8fa4ecc9982e0985829510274a951b022588e8be8c90e6fca5cbe23eb7edab8eR27

I don't fully understand the underlying implementation of or rationale behind this change, but obvious fix is updating [`GeometryCast`](https://github.com/MatanYadaev/laravel-eloquent-spatial/blob/a132345921fbccd2701d22b6d69d0c8cf38bfb7e/src/GeometryCast.php#L34-L48) to pass-through already-casted values.

Guessing the reason this was never encountered before is because Laravel caches casted values by default. Overriding `setRawAttributes` feels dangerous.

**Comment by MatanYadaev** [comment]
Hi @jbajou, your example doesn't appear to reproduce the bug.

I'm going to revert the latest changes to `setRawAttributes`, I know it means the serialization issue will return, but as other people said here, overriding `setRawAttributes` is not a good practice. I'll be happy to accept PRs and ideas on how to overcome this issue with a more elegant solution.

**Pull request merged**
